server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name _;
    root /app;

    # PHP-FPM status səhifəsi (phpfpm_* metrics üçün)
    location = /status {
        access_log off;
        fastcgi_pass 127.0.0.1:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_NAME /status;
        fastcgi_param SCRIPT_FILENAME "";
    }

    # Bütün digər request-lər index.php router-ə
    location / {
        fastcgi_pass 127.0.0.1:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
    }
}
